version: 2

on:
  workflow_dispatch:
  
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "18:00"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore/build: "
    reviewers:
      - "fetzu"
