baseURL = "https://www.marmotteproductions.ch/"
languageCode = "fr-CH"
title = "Marmotte Productions"
theme = "yourfolio"
disableKinds = [ "RSS" ]

[[menu.main]]
name = "News"
weight = 1
url = "/news"

[[menu.main]]
name = "Projets"
weight = 2
url = "/projets"

[[menu.main]]
name = "À propos"
weight = 3
url = "/apropos"

[[menu.main]]
name = "Contact"
weight = 4
url = "/contact"

[params]
env = "production"
logoImage = "img/logo.png"
logoImageAlt = "Marmotte Productions"
mainSections = ['news', 'projets']